---
title: "package"
author: "Brian S. Yandell"
date: "7/6/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

motivation for creating packages

- Fritz Leisch, Kurt Hornik: [CRAN](https://cran.r-project.org/), package format
- built on [CPAN](http://www.cpan.org/), [CTAN](https://www.ctan.org/?lang=en)
- CRAN mirrors

R package primer references

- Karl Broman: [R Package Primer](http://kbroman.org/pkg_primer/)
    + [Package Examples](https://github.com/kbroman/pkg_primer/tree/gh-pages/example)
- Hadley Wickham: [R Packages from O’Reilly](http://r-pkgs.had.co.nz/)
- Hilary Parker: [R Package Tutorial](http://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
- Writing Documentation
    + Karl Broman: [Writing documentation with Roxygen2](http://kbroman.org/pkg_primer/pages/docs.html)
    + Josh Paulson: [Writing Package Documentation](https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation)
- CRAN: [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)
- Jenny Bryan: [Writing your own R package](http://stat545-ubc.github.io/packages00_index.html)

R source package contents

- `DESCRIPTION` text file
- folders: `R`, `man`, `data`
- optional folders for added documentation: `inst`, `vignettes`
    + `inst` typically has sub-folder `doc` with `Rmd` files, etc.
- optional files: `NAMESPACE`
- `README.md`
- Rstudio project file: `myname.Rproj`
- `LICENSE`

R installed package contents

- takes source and moves to another place
